### ISSUE TITLE
The SDK gives implicit consent

### ISSUE THREAD

**Issue by bitsflew** [SourcePointUSA/ios-cmp-app#225] opened 2020-08-11 16:23 UTC
**Describe the bug**
The SDK gives implicit consent

** About your environment **
 - 5.2.5 and 5.2.6
 - iPhone8, iPadAir
 - iOS13.6

**To Reproduce**
1. Reinstall (to remove userdata) any app using the ConsentViewController
2. Wait for the consent window to appear
3. Force-quit the app whule the consent window is visible
4. Open the app again

**Expected behavior**
Consent window should appear
However gdprConsentUIWillShow not called but onConsentReady is!

**Comment by andresilveirah** [comment] 2020-08-12 06:57
Hi @bitsflew thank you for reporting. I wasn't able to reproduce this behaviour with the example property:
```
accountId: 22,
propertyId: 7639,
propertyName: "tcfv2.mobile.webview",
PMId: "122058",
campaignEnv: .Public
```
So I expect the issue to be in the scenario setup in our Dashboard. Can you share with me your property details? If you rather not do it publicly on GitHub, feel free to ping me in Slack or even send me an email andre at sourcepoint dot com.

**Comment by pwallrich** [comment] 2020-08-13 12:12
We had the same issue and reinitialising the message and everything in the sourcepoint web UI, with the exact same values worked. However, that shouldn't be a solution, since doing this in production wolud show the message to every user again, since it's a new campaign and message I guess.

**Comment by andresilveirah** [comment] 2020-08-13 14:23
You're correct @pwallrich . Re-starting a campaign in our Dashboard (even if nothing changed in the campaign) will effectively show the message to all users.

From a conversation with @bitsflew it seems the issue is no longer reproducible. @pwallrich were you experiencing the issue today or a few days back?

**Comment by pwallrich** [comment] 2020-08-14 05:50
It happened a few days back.

**Comment by andresilveirah** [comment] 2020-08-14 07:46
@pwallrich I'll close this issue for now, as I'm also not able to reproduce it. We'll keep an eye on it and if this problem shows up again we'll reopen the issue.

**Closed by andresilveirah** 2020-08-14 07:46 UTC
