### ISSUE TITLE
Version 6.5.0 doesn't build

### ISSUE THREAD

**Issue by Kislem** [SourcePointUSA/ios-cmp-app#372] opened 2022-03-22 16:52 UTC
I download the last Version of **ConsentViewController 6.5.0** via pod and try to build the app but the app **failed** to build.

**4 Errors:**

**ConsentViewController/Classes/SourcePointClient/GDPRPrivacyManagerViewResponse.swift:32:21: Value of optional type 'URL??' not unwrapped; did you mean to use 'try!' or chain with '?'?**

**ConsentViewController/Classes/SourcePointClient/SPNativeUI.swift:168:74: Cannot assign value of type 'URL???' to type 'URL?'**

**ConsentViewController/Classes/SourcePointClient/SPNativeUI.swift:200:20: Value of optional type 'String??' not unwrapped; did 
you mean to use 'try!' or chain with '?'?**

**ConsentViewController/Classes/SourcePointClient/SPPrivacyManagerRequestResponse.swift:24:25: Value of optional type 'URL??' not unwrapped; did you mean to use 'try!' or chain with '?'?**

**Comment by andresilveirah** [comment] 2022-03-23 10:02
Hi @Kislem I'm unable to reproduce your issue. I want to make sure I try to reproduce it in a setup as close as possible, can you tell me the version of the following components?
* XCode
* Swift
* Cocoapods
* Simulator / Real Device
* iOS / TvOS
* Your MacOS and processor type (M1 vs Intel)

**Comment by Kislem** [comment] 2022-03-23 10:26
Hi @André,

Thank you for your answer, you can find below the required components:


   - XCode = *13.2.1*
   - Swift = *5*
   - Cocoapods =* 1.11.2*
   - Simulator / Real Device = *simulator iphone 13 iOS 15.2*
   - iOS / TvOS: min *iOS 13*,* TvOS : 10.0*
   - Your MacOS and processor type (M1 vs Intel): *2,7 GHz Intel Core i7
   quatre cœurs*

Cordially
KIslem

Cordialement/Best regards
…………………………………………………
*ISLEM KAABI*
* iOS Developer *
M:  +33 7 72 06 59 03
E :  ***@***.***
…………………………………………………

Suivez Mon actualité sur les réseaux sociaux:
Facebook <https://www.facebook.com/Islem.kaabi1> I LinkedIN
<https://www.linkedin.com/in/islem-kaabi-7ab33a76>



Le mer. 23 mars 2022 à 11:02, André Herculano ***@***.***> a
écrit :

**Comment by andresilveirah** [comment] 2022-05-06 14:38
@Kislem I'm closing this issue as I believe it should've been fixed by now. Let me know if that's not the case.

**Closed by andresilveirah** 2022-05-06 14:38 UTC
