### ISSUE TITLE
[SPRING] At the first start of the app the CMP SDK calls onConsentReady instead of consentUIWillShow

### ISSUE THREAD

**Issue by toupper** [SourcePointUSA/ios-cmp-app#226] opened 2020-08-13 13:47 UTC
**Describe the bug**
At the first start of the app we are expecting that the CMP SDK calls` func consentUIWillShow(message: GDPRMessage) `with the message, so we can show the Native Consent Layer (WELT) Instead `onConsentReady`, with an all false userConsent.
**About your campaign (please complete the following information):**
 - Account Id 75
 - Property Id 4598
 - Property Name "WELT-NEWS-IOS"
-  PMId "134094"
 - Campaign Env

** About your environment **
 - SDK version 5.2.6
 - Device: iPhone 8
 - OS: 13.6

**To Reproduce**
1. Make an app clean install
2. Start the app 

**Expected behavior**
consentUIWillShow it is called instead of onConsentReady

**Comment by andresilveirah** [comment] 2020-08-13 14:25
Hi @toupper I've tried reproducing the issue above but no luck. Here's how I initialised the SDK:
```swift
    lazy var consentViewController: GDPRConsentViewController = { return GDPRConsentViewController(
        accountId: 75,
        propertyId: 4598,
        propertyName: try! GDPRPropertyName("WELT-NEWS-IOS"),
        PMId: "134094",
        campaignEnv: .Public,
        consentDelegate: self
    )}()
```

What's the `campaignEnv` you're using?

**Comment by toupper** [comment] 2020-08-13 14:26
@andresilveirah also .Public

**Comment by andresilveirah** [comment] 2020-08-14 07:47
@toupper are you using `.loadNativeMessage` or `.loadMessage`. Also, are you using authenticated consent?

**Comment by toupper** [comment] 2020-08-14 07:56
@andresilveirah We are using `loadNativeMessage` without authenticated consent:
`consentManagementPlatform.loadNativeMessage(forAuthId: nil)`

**Comment by andresilveirah** [comment] 2020-08-14 10:59
@toupper that's strange. I see the message every time I launch the app (including the very first time after install). Are you able to provide me with an sample app in which the issue is reproducible?

**Comment by toupper** [comment] 2020-08-14 14:22
@andresilveirah I debugged it a little further, and seems like the backend is not returning any message for the first request, but all the consent. This is the body of the request:

```
{
	"campaignEnv": "prod",
	"accountId": 75,
	"targetingParams": "{}",
	"propertyHref": "https:\/\/WELT-NEWS-IOS",
	"uuid": "",
	"requestUUID": "E2889414-9E8B-447A-992C-838239603F22",
	"meta": "{}",
	"propertyId": 4598,
	"euconsent": ""
}
```
Attached you can find a document attached with the complete url and body, and the response.If you want we can have a live debug session where we can see the problem.

[Issue226.pdf](https://github.com/SourcePointUSA/ios-cmp-app/files/5075060/Issue226.pdf)

**Comment by andresilveirah** [comment] 2020-08-15 08:33
Thanks @toupper . I just plugged that same request on Postman and the SDK, I get a different response than you do. Most importantly, I get a response in which the `msgJSON` is filled in. I've sent you an invite so we can pair and find out what's going on.

**Comment by andresilveirah** [comment] 2020-08-17 09:14
Just to keep info centralised here. @toupper and I had a call and the issue seems to be in the geo targeting step of the scenario. Our backend team will look into it and I'll keep this thread updated once we have any news.

**Comment by pkcpkc** [comment] 2020-08-24 09:03
@andresilveirah Any updates here? Is everything working? Can this ticket be closed?

**Comment by pkcpkc** [comment] 2020-08-24 09:24
[11:23] Munoz, Carolina
    Hab getestet, Hackenberger, Paul mit Earth VPN. Siehst du noch irgendwo offene Punkte? Aus Uruguay und Südafrika sieht das alles okay aus (smile)

**Comment by andresilveirah** [comment] 2020-08-24 10:38
@pkcpkc I know our backend colleagues are working to improve the geo targeting service. I'll keep this issue open until their work is finished. Long story short, we use ip-lookup to determine the location of the user. Sometimes, new IPs (such as the one our friend César) won't be recognised in the IP database and, if the scenario has a condition to show message only to people in the GDPR area, then it won't show the message, calling the `onConsentReady` right away.

**Comment by haerju** [comment] 2020-09-08 11:36
@andresilveirah @toupper @pkcpkc The geo locaction targeting step has been removed from you targeting scenarios in the admin portal. This has been done because of Axel Springer policy reason. We still have an open to shore up our geo location targeting but I am closing this ticket for now since it shouldn't affect you any longer.

**Comment by andresilveirah** [comment] 2020-09-08 11:37
Thanks for the feedback @haerju

**Closed by andresilveirah** 2020-09-08 11:37 UTC
