### ISSUE TITLE
[NMT] privacy manager - overlapping layer with status bar

### ISSUE THREAD

**Issue by FSchanbacher** [SourcePointUSA/ios-cmp-app#256] opened 2020-10-20 12:11 UTC
We now see a transparent layer on half of status bar when opening privacy manager on different devices (on first pm layer + in Drittanbieter/3rd party), looks fine in section 'Berechtigtes Interesse'

Account Id: 75
Property Id 5593
Property Name BILD-NEWS-IOS
PrivacyManager Id: 134100

** To Reproduce**
open privacy manager on iphones

first layer pm (not ok):
![pm-first-layer-not-ok](https://user-images.githubusercontent.com/39551150/96583879-b04f6e00-12dd-11eb-89b3-bb5db890d57e.png)

3rd party (not ok):
![3rd-party-not-ok](https://user-images.githubusercontent.com/39551150/96583873-af1e4100-12dd-11eb-9094-9eaa580fb356.png)

legitimate interest (ok):
![legitimate-interest-ok](https://user-images.githubusercontent.com/39551150/96583881-b0e80480-12dd-11eb-96c7-d3dc2c64af59.png)

**Comment by haerju** [comment] 2020-10-25 19:22
@FSchanbacher I am not able to reproduce this issue in our Meta App any longer. However, we are going to put one additional fix in, that should safe guard against any other app specific use case. ETA mid of w/c 10/25

**Comment by FSchanbacher** [comment] 2020-11-03 13:00
the legitimate interest section is movable and then overlaps again with the status bar

**Comment by haerju** [comment] 2020-11-05 23:58
@FSchanbacher Yes, applying the safe area breaks those parts of the messaging experience that were already fixed by using custom CSS on the messages. We have a freature in QA that enables us to apply the safe area restrictions more selectively on a per message basis.

**Comment by haerju** [comment] 2020-11-17 05:26
@FSchanbacher As discussed we implemented the safe area feature and I made a few tweaks to the messages to expand the width of the privacy manager in landscape mode. The only problem is just that our meta app doesn't support landscape mode yet, so I am somewhat limited in testing the experience with your messages. I launched a STAGE campaign for the BILD-NEWS-IOS property for you to test. Are you able to change the SDK config param to stage? Please also note the PM ID for this test is 384959.

**Comment by FSchanbacher** [comment] 2020-11-17 11:09
@haerju I am not able to change the config param to stage. how can that be done?
I can change the pm id in our config locally (also propertyID or accountID)

**Comment by FSchanbacher** [comment] 2020-11-18 14:39
I was able to adjust the code to make use of the stage environment now.

Consent layer (with described problem here: https://github.com/SourcePointUSA/ios-cmp-app/issues/258) looks fine now.

PM isn't perfect yet. When entering PM, the 2nd button is cut and the whole view is movable (also in legitimate interest category & partners). What I would prefer here is that the PM should be a little bit smaller in height so that the buttons aren't cut and it should not be movable itself. Scrolling within the PM through different vendors is fine and works but a movable layer around this is not good.

See how it looks like now here:

![pm-after-opening-on-iphone-x](https://user-images.githubusercontent.com/39551150/99543977-151ce780-29b4-11eb-8ea3-8dd98c697cef.png)
![pm-scrolled](https://user-images.githubusercontent.com/39551150/99543988-1b12c880-29b4-11eb-859c-cd5ebb97f872.png)

**Comment by haerju** [comment] 2020-11-24 04:01
@FSchanbacher Thanks for the additional feedback. I made the privacy manager non-scrollable and decreased the height to bring the call to to actions up a little higher. I also added a more margin at the bottom of the 1st layer message to have a cleaner separation between the home button and the links to the data privacy terms and Impressum. Everything looks fine in x-code for me. Take a look and let me know if you want to launch the new message into public and we can work with Eileen to get this released.

**Comment by FSchanbacher** [comment] 2020-11-25 11:32
@haerju 
- looks better now but the legitimate interest section is still movable (first pm layer  + 3rd party is fine).
- when switching from first pm layer to legitimate interest you can also see that the height of the whole view is increased a bit which is not happening when switching between first pm layer and 3rd party section
- no overlapping anymore with the StatusBar ✅

**Comment by andresilveirah** [comment] 2021-05-21 12:19
Closing due to inactivity.

**Closed by andresilveirah** 2021-05-21 12:19 UTC
