### ISSUE TITLE
[SPRING] VendorGrants of UserConsent is empty after customConsentTo

### ISSUE THREAD

**Issue by toupper** [SourcePointUSA/ios-cmp-app#195] opened 2020-06-23 15:17 UTC
I am using CMP SDK for iOS version 5.2.2 After enable some consent via the method `customConsentTo` i get a refreshed  `userConsent` in the `completionHandler` , however the `vendorGrants` property is empty :warning:. When I restart the app and retrieve the `userConsent` via the `onConsentReady` delegate method `vendorGrants` is filled again with its values as expected.

**Comment by andresilveirah** [comment] 2020-06-24 13:54
Hi @toupper thanks for reporting, I'm able to reproduce this issue. We'll start working on it right away.

**Comment by andresilveirah** [comment] 2020-06-25 14:47
@toupper we're releasing shortly `5.2.4` with a fix for this issue.

**Comment by toupper** [comment] 2020-06-26 14:18
Now the `vendorGrants` attribute of `userConsent` is filled, however the values are not updated with the new state after `customConsentTo`.When I restart the app and retrieve the `userConsent` via the `onConsentReady` delegate method vendorGrants is filled again with the updated values. Please see attached file with the XCode console logs.

[CMPIssue195.pdf](https://github.com/SourcePointUSA/ios-cmp-app/files/4837408/CMPIssue195.pdf)

**Comment by andresilveirah** [comment] 2020-06-26 14:33
I'll have a look with our backend engineers @toupper . As soon as I have more info I'll let you know.

**Comment by andresilveirah** [comment] 2020-06-29 12:46
@toupper I can indeed reproduce the issue you reported (the vendor grants not being updated). I've created a ticket for our backend folks and, as soon as I have more info I'll let you know.

**Comment by matance** [comment] 2020-07-06 09:49
Hello, is there any new info on this issue? Thanks

**Comment by andresilveirah** [comment] 2020-07-06 10:00
Hi @matance , a fix for this issue is currently being QAed. Although I don't have a concrete ETA on it, I believe it should be released in the next 1-2 days. I'll keep you posted as soon as the fix is out.

**Comment by matance** [comment] 2020-07-14 10:28
Hi @andresilveirah, it has been already a week since your last comment. Any news on this?

**Comment by ivanlisovyi** [comment] 2020-07-20 08:27
Hi @andresilveirah, do you have any updates on this issue? It's a release blocker for us and it would be very nice if you can share more info about the progress with us. Thank you in advance!

**Comment by andresilveirah** [comment] 2020-07-20 08:34
Hi @ivanlisovyi @matance I'm sorry I let this one slip last week. I can see the fix has been QAed in staging and is now pending deploy to production. Let me try to annoy the right people via slack and get this pushed either today EOD.

**Comment by andresilveirah** [comment] 2020-07-20 11:45
@ivanlisovyi @matance I just got from a call with our VP of engineering. There are a few things being deployed at the same time to production and, because of that, the QA process is taking a bit longer than usual. According to him, if everything goes well, the fix for this issue should be deployed by tomorrow EOD.

**Comment by andresilveirah** [comment] 2020-07-22 14:09
@ivanlisovyi @matance the fix was not deployed yesterday (as you might have realised) but I have reasons to believe it should be released today (I know it's the 3rd time I'm saying that and believe me, it's frustrating for me too...). I'll keep you informed.

**Comment by andresilveirah** [comment] 2020-07-24 15:44
@ivanlisovyi @matance @toupper it finally happened... Can you verify the vendor grants are now updated after you call the `customConsentTo` method?

**Comment by ivanlisovyi** [comment] 2020-07-27 12:10
@andresilveirah I've checked the iOS SDK and it seems to be working. Thanks!

**Comment by andresilveirah** [comment] 2020-07-28 08:35
@ivanlisovyi really glad to know that. Thanks for the patience.

**Closed by andresilveirah** 2020-07-28 08:35 UTC

**Comment by hameno** [comment] 2020-07-28 10:55
I'm having the same problem on Android, the GDPRUserConsent object returned from customConsentTo does not reflect the new vendorGrants. After restarting the app, I get the updated vendorGrant. I created an issue on the Android project: https://github.com/SourcePointUSA/android-cmp-app/issues/221

**Comment by andresilveirah** [comment] 2020-07-28 11:09
Thank you for reporting @hameno That seems odd to me since both SDKs use the same API. Maybe there's something weird going on on our Android code. We'll check and follow up in the issue on Android's repo.
